//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automation.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat
        ///	set procs to &quot;&quot;
        ///	tell application &quot;System Events&quot;
        ///		set procs to name of every process
        ///	end tell
        ///	if procs contains &quot;SecurityAgent&quot; then
        ///		tell application &quot;System Events&quot;
        ///			tell process &quot;SecurityAgent&quot; to set value of text field 1 of scroll area 1 of group 1 of window 1 to &quot;$USERNAME&quot;
        ///			tell process &quot;SecurityAgent&quot; to set value of text field 2 of scroll area 1 of group 1 of window 1 to &quot;$PASSWORD&quot;
        ///			click button 2 of group 2 of window 1 of application process &quot;SecurityAgent&quot;
        ///			log (&quot;Dismissed S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BeatSecurityAgent {
            get {
                return ResourceManager.GetString("BeatSecurityAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ***** helper functions ***** */
        ///
        ///// delay in seconds
        ///function delay(secs)
        ///{
        ///	var date = new Date();
        ///	var curDate = null;
        ///	
        ///	do { curDate = new Date(); }
        ///	while(curDate-date &lt; (secs * 1000.0));
        ///} 
        ///
        ///// find cell with name
        ///function findCellWithName(cellName, window) {
        ///	
        ///	return window.visibleCells()[cellName];
        ///	
        ///	for (index = 0; index &lt; window.tableViews().length; index = index + 1) {
        ///		cell = window.tableViews()[index].visibleCells()[cellName];
        ///		if ((cell != null) &amp;&amp; (cell.toString() != [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap {
            get {
                return ResourceManager.GetString("bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #! /usr/bin/python
        ///
        ///from sys import argv
        ///
        ///f = open (argv[1],&apos;w&apos;)
        ///for arg in argv[2:]:
        ///	f.write(arg)
        ///f.close()
        ///
        ///.
        /// </summary>
        internal static string writeResponse {
            get {
                return ResourceManager.GetString("writeResponse", resourceCulture);
            }
        }
    }
}
